#:kivy 1.10.0

<AppScreenManager>:
    AudiosScreen:

<AudiosScreen>:
    view: view

    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            size: (64, 64)
            size_hint: (1, None)

            Label:
                id: intro_label
                text: "ds"
                font_size: 24
                bold: True
                color: .47, 1, .56, 1

        ScrollView:
            id: view